### PR TITLE
Why should  plugin skip core application AppController?

### PR DESCRIPTION
**Pull request by hekep**
Why should  plugin controller  skip core application AppController?

I want to do in my core Application / AppController:
$this->response->withHeader('Access-Control-Allow-Origin', 'https://*.mysite.com');

And this should affect application wide.  SwaggerController skips core App / AppController and therfore has no effect of 'Access-Control-Allow-Origin' .  This is why "Try it out" did not work in Firefox broswer.

### CODE REVIEW

**Comment by hekep** [comment]
More accureate code for core App AppController.php

```
$this->response = $this->response->cors($this->request)
                ->allowOrigin(['*.primanda.fi'])->build();
```

**Comment by cnizzardini** [comment]
Read this: https://github.com/cnizzardini/cakephp-swagger-bake#extending-views-and-controllers

Just create your own SwaggerController and don't use the one included.

**Comment by hekep** [comment]
Does that mea,n that whenever I update your plugin I have to disable / delete your original controller, because it is not extending core App AppController.php ?  AFAIK your original controller still provides access to app users. Anyone can try cold URLs.  

If your plugin Controller is meant to be template, then it should it be in some other folder than  plugins `src/Controllers/`  ?   

`bin/cake swagger bakeSwaggerController`  ?

**Comment by cnizzardini** [comment]
Most of the logic needed is in a Component so change is less likely. That controller hasn't changed in over a year, but if you are needing to customize things it's possible it could change at some point in a major release and you'd have to spend a few minutes fixing your application.

**Comment by hekep** [comment]
I am still worried about your plugin original  src/Controller/SwaggerController.php  being available "to the public" 

I it will end up to ACL lists, if we scan application controllers. This is why I asked should I delete your original controller, if its meant to be only template for the core application.

**Comment by cnizzardini** [comment]
It's not meant to be only a template. It is the default controller for your swagger or redoc ui, but you have the option of using your own and adding in what ever logic your application needs.

**Comment by cnizzardini** [comment]
Try it out works fine in the public demo: https://cakephpswaggerbake.cnizz.com

**Comment by hekep** [comment]
> 
> 
> Try it out works fine in the public demo: https://cakephpswaggerbake.cnizz.com

@cnizzardini  you are running the demo application from Apache server , here are the headers: 
kuva

I am running swagger via cakephp bin/server and I get the following headers:

kuva

When I do  "Try It out" , the CsrfProtectionMiddleware jumps in and I get this from API:

{
    "message": "Missing or incorrect CSRF cookie type.",
    "url": "\/api\/terms",
    "code": 403,
    "file": "\/data\/srv\/www\/some_host\/public_html\/my_project\/vendor\/cakephp\/cakephp\/src\/Http\/Middleware\/CsrfProtectionMiddleware.php",
    "line": 381
}

Then I disable  CsrfProtectionMiddleware.

After that I get 500 because of:

{
    "message": "Argument 1 passed to App\\Controller\\AppController::App\\Controller\\{closure}() must be an instance of App\\Controller\\BadRequestException, instance of Cake\\Http\\Exception\\BadRequestException given, called in \/data\/srv\/www\/mydev_host\/public_html\/my_project\/vendor\/cakephp\/cakephp\/src\/Controller\/Component\/FormProtectionComponent.php on line 164",
    "url": "\/api\/payment-terms",
    "code": 500,
    "file": "\/data\/srv\/www\/mydev_host\/public_html\/my_project\/src\/Controller\/AppController.php",
    "line": 70
}

I disable  $this->loadComponent('FormProtection');  in AppController and I get futher finally to "Record not created" in corresponging Controller/action method. I'll check how to get validation errors included into \Exception("Record not saved").

Is it any meaningful to embed the Swagger Pugin into  actual Cakephp Application?

**Pull request closed without merging**
