### PR TITLE
Windows support | Initial work

### PR DESCRIPTION
**Pull request by ArchangelDesign**
The main idea is to have unit tests pass on Windows with no problems.
There are many assertions regarding paths that are not consistent. One example is the path starting with `DS` to be later evaluated that it needs to start with `/`.
This is not the easiest task as some parts of the path come from the environment and the others from the config file resulting in paths like `C:\path\directory/another-directory/file.json`

I'm submitting PR to check the branch against the pipeline to make sure those issues do not result from updated dependencies.

### CODE REVIEW

**Comment by cnizzardini** [comment]
Did you mean to set the base to `master` instead? This is set to `v3.0.0` base. That branch is meant for cakephp 5 + php 8.1 which won't be released until later this year.

**Comment by cnizzardini** [comment]
Aww shit this is all fucked up now haha.

**Comment by ArchangelDesign** [comment]
this is bumped from 3.0.0, which was my intention, we're not upgrading to PHP 8.1 until next year so I don't need those changes in master yet. I ran tests on master and have 34 failures, mostly `TypeError` (on top of Windows-related issues)

**Comment by cnizzardini** [comment]
> this is bumped from 3.0.0, which was my intention, we're not upgrading to PHP 8.1 until next year so I don't need those changes in master yet. I ran tests on master and have 34 failures, mostly `TypeError` (on top of Windows-related issues)

Okay, I have no idea when version 3 of this library will go out. That is dependent on CakePHP 5: https://github.com/cakephp/cakephp/wiki/5.0-Roadmap and I imagine that won't be released until EOY at best. 

If you want windows to be testable in the current master branch I suggest doing the changes there and I will handle merging into v3.0.0. Up to you though.

**Comment by cnizzardini** [comment]
Sidenote. I will never test on windows. Can windows be included in github actions pipeline?

**Comment by ArchangelDesign** [comment]
Yeah, that's fine, I'll submit another PR for master since there are other issues with that one. I doubt I'll be switching from `1.next` this year so there is no rush on my side.

Windows in the pipeline? I have never seen that :)
I don't think it's required for this lib to work on Windows, I'm doing it only to be able to work on it on my rig :) I imagine I might not be the only one either.

**Comment by ArchangelDesign** [comment]
oh, I just noticed I decreased coverage (by adding that trait), I'll add test for that.

**Comment by ArchangelDesign** [comment]
all tests pass on Windows

**Comment by ArchangelDesign** [comment]
overengineered and didn't really solve the problem.

**Pull request closed without merging**
