### PR TITLE
Make sure controller name is uppercase so the fqm is located in the c…

### PR DESCRIPTION
**Pull request by ArchangelDesign**
When `loadRoutes()` is invoked, it scans all routes and manually builds namespace to later find it in the class-map.
Not sure how it worked before, but `$routeDecorator->getController()` will return lowercase name of the controller (cake 4.4) thus route is not found and no routes are generated.
I can't use the latest version yet as I'm restricted to PHP 7.4 at the moment. On the other hand, I prefer to have no documentation than maintaining the YML file myself :) 

All tests are passing (not on WIndows though, DS is hardcoded to `/` so some assertions fail),
Code sniffer is complaining about EOL characters on my machine (gotta love WIndows) but I doubt that will be a problem (easily fixed).

### CODE REVIEW

**Comment by cnizzardini** [comment]
Can you fix these failures? Looks to be all the same thing and unrelated to code @ArchangelDesign.

**Comment by cnizzardini** [comment]
And this is strange that it was working in 4.3 but not 4.4.... I wonder what changed. I haven't used version 1 of this in months.

**Comment by ArchangelDesign** [comment]
@cnizzardini looks like the codesniffer should be updated, do you want me to handle that?

**Comment by cnizzardini** [comment]
That PHPMD warning can just be ignored: 
- https://phpmd.org/documentation/suppress-warnings.html 
- https://phpmd.org/rules/controversial.html#camelcasepropertyname

**Comment by cnizzardini** [comment]
> @cnizzardini looks like the codesniffer should be updated, do you want me to handle that?

If you are okay with that work that may needed, up to you.

**Comment by ArchangelDesign** [comment]
hmm, that didn't work...

**Comment by cnizzardini** [comment]
Just pull in 1.next, I resolved this phpmd annoyance here https://github.com/cnizzardini/cakephp-swagger-bake/pull/431 and merged it in. Also added 4.3 and 4.4 respectively to the ci matrix.

**Comment by cnizzardini** [comment]
I am confused why none of the unit tests failed in https://github.com/cnizzardini/cakephp-swagger-bake/pull/431 though when running against cakephp 4.4. I don't understand how this bug popped up and why tests wouldn't catch it. You are sure this wasn't a problem in cakephp 4.3 and there are no other changes in your userland code that would cause this?

For shits and giggles I dropped by php version to 7.4, checked out this tag in the demo app: https://github.com/cnizzardini/cakephp-swagger-bake-demo/tree/v1.7.5 and then ran a `composer update`. I then handled the 4.4 deprecation's of the old error handlers in `config/bootstrap.php`. The app worked as expected once I did that.

**Comment by ArchangelDesign** [comment]
I'll add the test case to reproduce it.
```
$builder->get('/', ['controller' => 'index', 'action' => 'theAction']);
```
The controller will still be located as `App\Controller\IndexController` regardless of lowercase `i`

**Comment by ArchangelDesign** [comment]
I wasn't sure how to go around the deprecation of `scope()` in the router so I just replicated your use case. I added the route with a lowercase controller name which results in fqn being null.

**Comment by ArchangelDesign** [comment]
Just for the background info, the cake will convert the controller name to PascalCase (called CamelCase in the code, which is not correct) even if provided in snake_case.
https://github.com/cakephp/cakephp/blob/4.x/src/Routing/Route/DashedRoute.php#L71
The documentation presents examples of PascalCase controllers but it is not specified nor enforced.

**Comment by cnizzardini** [comment]
@ArchangelDesign v1.7.7 has been released.

**Comment by ArchangelDesign** [comment]
@cnizzardini thank you, updated on my side and working great.
Great job on this lib btw.

**Pull request merged**
