### PR TITLE
Update PropertyDecorator.php

### PR DESCRIPTION
**Pull request by lpj145**
This decorator get a error when default value is a 0 or 1, example, postgres booleans columns.

### CODE REVIEW

**Comment by lpj145** [comment]
Please, sorry for make pr direct, but for me is a simple  small case, thank you.

**Comment by cnizzardini** [comment]
I am putting together a 1.5.6 release, this will go out with that. Thanks.

**Comment by lpj145** [comment]
https://github.com/lpj145/cakephp_template/tree/main special thanks for you, because this package i can grow consistent and documented ahahah, this template is powered to fast rest api development.

**Comment by cnizzardini** [comment]
More things coming: https://github.com/mixerapi

**Comment by lpj145** [comment]
> More things coming: https://github.com/mixerapi

I see, congratulations for you hard work, i don't like hal and json-ld, but i want to be help in another packages.

**Pull request merged**
